# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# Uncomment this line if you're using Swift
use_frameworks!

target 'HappyFeet' do
	pod 'Masonry'
	pod 'Charts'
	pod "TextFieldEffects"
	pod "ImagePickerSheetController", "~> 0.9.1"
end

